import enum


class FieldType(enum.StrEnum):
    SHORT_TEXT = "SHORT_TEXT"
    PARAGRAPH = "PARAGRAPH"
    MULTIPLE_CHOICE = "MULTIPLE_CHOICE"
    DROPDOWN = "DROPDOWN"
    FILE_UPLOAD = "FILE_UPLOAD"
    DATE = "DATE"
    NUMBER = "NUMBER"


class JobStatus(enum.StrEnum):
    DRAFT = "DRAFT"
    LIVE = "LIVE"
    CLOSED = "CLOSED"
    PROCESSED = "PROCESSED"


class SubmissionStatus(enum.StrEnum):
    SUBMITTED = "SUBMITTED"
    PARSED = "PARSED"
    RANKED = "RANKED"
    INVITED = "INVITED"
    CONFIRMED = "CONFIRMED"
    DECLINED = "DECLINED"
    REJECTED = "REJECTED"
    RESCHEDULED = "RESCHEDULED"
    PARSE_ERROR = "PARSE_ERROR"


class SlotStatus(enum.StrEnum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    DECLINED = "DECLINED"
    RESCHEDULED = "RESCHEDULED"
    CANCELLED = "CANCELLED"


class EmailType(enum.StrEnum):
    APPLICATION_CONFIRMATION = "APPLICATION_CONFIRMATION"
    INTERVIEW_INVITE = "INTERVIEW_INVITE"
    INTERVIEW_RESCHEDULE = "INTERVIEW_RESCHEDULE"
    CANCELLATION = "CANCELLATION"
    REJECTION = "REJECTION"
    CUSTOM = "CUSTOM"


class DeliveryStatus(enum.StrEnum):
    SENT = "SENT"
    FAILED = "FAILED"
    PENDING = "PENDING"


class TaskType(enum.StrEnum):
    RESUME_PARSE = "RESUME_PARSE"
    BATCH_RANKING = "BATCH_RANKING"
    EMAIL_DISPATCH = "EMAIL_DISPATCH"
    CALENDAR_SYNC = "CALENDAR_SYNC"
    JD_EMBEDDING = "JD_EMBEDDING"


class TaskStatus(enum.StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    RETRIED = "RETRIED"


class Weekday(enum.StrEnum):
    MONDAY = "MONDAY"
    TUESDAY = "TUESDAY"
    WEDNESDAY = "WEDNESDAY"
    THURSDAY = "THURSDAY"
    FRIDAY = "FRIDAY"
    SATURDAY = "SATURDAY"
    SUNDAY = "SUNDAY"
