/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Login */
        get: operations["google_login_api_v1_auth_google_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/reconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Reconnect
         * @description Restart consent for the logged-in recruiter. Reuses the same state-binding
         *     CSRF cookie as /google/login; the existing /google/callback + upsert_recruiter
         *     already replace the stored tokens and flip account_state back to ACTIVE
         *     (retaining the existing refresh token if Google omits a new one).
         */
        get: operations["google_reconnect_api_v1_auth_google_reconnect_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Callback */
        get: operations["google_callback_api_v1_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description No get_current_recruiter dependency, deliberately — logout must be
         *     idempotent with no session (AC-02), not 401. Safe without CSRF protection
         *     because the session cookie is SameSite=Lax: a cross-site POST doesn't carry
         *     it, so an attacker can't trigger this against a logged-in victim.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recruiters/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_v1_recruiters_me_patch"];
        trace?: never;
    };
    "/api/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_api_v1_templates_get"];
        put?: never;
        /** Create Template */
        post: operations["create_template_api_v1_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Template */
        get: operations["get_template_api_v1_templates__template_id__get"];
        /**
         * Replace Template
         * @description Replaces the full field set: the client sends the whole ordered array,
         *     the server reconciles it against existing rows by `field_id` (keep/update
         *     when present, insert when absent, delete when missing from the payload) —
         *     this is not a partial update.
         */
        put: operations["replace_template_api_v1_templates__template_id__put"];
        post?: never;
        /** Delete Template */
        delete: operations["delete_template_api_v1_templates__template_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Job */
        patch: operations["update_job_api_v1_jobs__job_id__patch"];
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Process */
        post: operations["trigger_process_api_v1_jobs__job_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/process/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Process Status */
        get: operations["process_status_api_v1_jobs__job_id__process_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/rank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Rank */
        post: operations["trigger_rank_api_v1_jobs__job_id__rank_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/apply/{apply_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Public Job */
        get: operations["get_public_job_api_v1_public_apply__apply_slug__get"];
        put?: never;
        /** Submit Application */
        post: operations["submit_application_api_v1_public_apply__apply_slug__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Candidates */
        get: operations["list_candidates_api_v1_jobs__job_id__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/candidates/ranked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ranked Candidates */
        get: operations["list_ranked_candidates_api_v1_jobs__job_id__candidates_ranked_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidates/{candidate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Candidate */
        get: operations["get_candidate_api_v1_candidates__candidate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Candidate */
        patch: operations["update_candidate_api_v1_candidates__candidate_id__patch"];
        trace?: never;
    };
    "/api/v1/candidates/{candidate_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Resume */
        get: operations["download_resume_api_v1_candidates__candidate_id__resume_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scheduling/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["get_preferences_api_v1_scheduling_preferences_get"];
        /** Update Preferences */
        put: operations["update_preferences_api_v1_scheduling_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scheduling/available-slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Available Slots */
        get: operations["available_slots_api_v1_scheduling_available_slots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Interviews */
        get: operations["list_interviews_api_v1_interviews_get"];
        put?: never;
        /** Schedule Interviews */
        post: operations["schedule_interviews_api_v1_interviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interviews/{slot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Interview */
        patch: operations["update_interview_api_v1_interviews__slot_id__patch"];
        trace?: never;
    };
    "/api/v1/emails/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Email */
        post: operations["send_email_api_v1_emails_send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/emails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Emails */
        get: operations["list_emails_api_v1_emails_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApplySuccessOut
         * @description No candidate_id: an internal UUID has no business reaching an
         *     unauthenticated caller, same reasoning as PublicJobOut.
         */
        ApplySuccessOut: {
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Message */
            message: string;
        };
        /**
         * AvailableSlotOut
         * @description Computed and bounded by ?count=, never Page[T] (ADR-004 P5).
         */
        AvailableSlotOut: {
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
        };
        /** Body_submit_application_api_v1_public_apply__apply_slug__post */
        Body_submit_application_api_v1_public_apply__apply_slug__post: {
            /** Resume */
            resume: string;
        };
        /** CandidateDetailOut */
        CandidateDetailOut: {
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            /** Phone Number */
            phone_number: string | null;
            submission_status: components["schemas"]["SubmissionStatus"];
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Parse Error */
            parse_error: string | null;
            /** Resume Url */
            resume_url: string | null;
            /** Form Responses */
            form_responses: components["schemas"]["FormResponseOut"][];
        };
        /** CandidateOut */
        CandidateOut: {
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            /** Phone Number */
            phone_number: string | null;
            submission_status: components["schemas"]["SubmissionStatus"];
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Parse Error */
            parse_error: string | null;
            /** Resume Url */
            resume_url: string | null;
        };
        /** CandidateUpdate */
        CandidateUpdate: {
            submission_status: components["schemas"]["SubmissionStatus"];
        };
        /**
         * DeliveryStatus
         * @enum {string}
         */
        DeliveryStatus: "SENT" | "FAILED" | "PENDING";
        /** EmailLogOut */
        EmailLogOut: {
            /**
             * Email Id
             * Format: uuid
             */
            email_id: string;
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /** Candidate Name */
            candidate_name: string;
            email_type: components["schemas"]["EmailType"];
            /** Subject */
            subject: string;
            /** Body Preview */
            body_preview: string | null;
            delivery_status: components["schemas"]["DeliveryStatus"];
            /**
             * Sent At
             * Format: date-time
             */
            sent_at: string;
            /** Is Automated */
            is_automated: boolean;
        };
        /** EmailSendIn */
        EmailSendIn: {
            email_type: components["schemas"]["EmailType"];
            /** Candidate Ids */
            candidate_ids: string[];
            /** Subject */
            subject?: string | null;
            /** Body */
            body?: string | null;
        };
        /**
         * EmailType
         * @enum {string}
         */
        EmailType: "APPLICATION_CONFIRMATION" | "INTERVIEW_INVITE" | "INTERVIEW_RESCHEDULE" | "CANCELLATION" | "REJECTION" | "CUSTOM";
        /** ErrorOut */
        ErrorOut: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * FieldType
         * @enum {string}
         */
        FieldType: "SHORT_TEXT" | "PARAGRAPH" | "MULTIPLE_CHOICE" | "DROPDOWN" | "FILE_UPLOAD" | "DATE" | "NUMBER";
        /** FormResponseOut */
        FormResponseOut: {
            /**
             * Field Id
             * Format: uuid
             */
            field_id: string;
            /** Field Label */
            field_label: string;
            field_type: components["schemas"]["FieldType"];
            /** Response Value */
            response_value: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InterviewCreate */
        InterviewCreate: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Candidate Ids */
            candidate_ids: string[];
        };
        /** InterviewSlotOut */
        InterviewSlotOut: {
            /**
             * Slot Id
             * Format: uuid
             */
            slot_id: string;
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /** Candidate Name */
            candidate_name: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /** Duration Minutes */
            duration_minutes: number;
            status: components["schemas"]["SlotStatus"];
            /** Google Meet Link */
            google_meet_link: string | null;
        };
        /** InterviewSlotUpdate */
        InterviewSlotUpdate: {
            status?: components["schemas"]["SlotStatus"] | null;
            /** Scheduled At */
            scheduled_at?: string | null;
            /** Reschedule Reason */
            reschedule_reason?: string | null;
        };
        /** JobCreate */
        JobCreate: {
            /** Job Title */
            job_title: string;
            /** Job Description */
            job_description: string;
            /**
             * Template Id
             * Format: uuid
             */
            template_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** JobDetailOut */
        JobDetailOut: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Job Title */
            job_title: string;
            status: components["schemas"]["JobStatus"];
            /** Is Accepting Responses */
            is_accepting_responses: boolean;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Submission Count */
            submission_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Job Description */
            job_description: string;
            /**
             * Template Id
             * Format: uuid
             */
            template_id: string;
            /** Apply Slug */
            apply_slug: string;
            /** Apply Url */
            apply_url: string;
            /** Google Drive Folder Id */
            google_drive_folder_id: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Submission Counts */
            submission_counts: {
                [key: string]: number;
            };
            /** Processed At */
            processed_at: string | null;
        };
        /** JobOut */
        JobOut: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Job Title */
            job_title: string;
            status: components["schemas"]["JobStatus"];
            /** Is Accepting Responses */
            is_accepting_responses: boolean;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Submission Count */
            submission_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Apply Url */
            apply_url: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "DRAFT" | "LIVE" | "CLOSED" | "PROCESSED";
        /** JobUpdate */
        JobUpdate: {
            /** Job Title */
            job_title?: string | null;
            /** Job Description */
            job_description?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Is Accepting Responses */
            is_accepting_responses?: boolean | null;
            status?: components["schemas"]["JobStatus"] | null;
        };
        /** Page[CandidateOut] */
        Page_CandidateOut_: {
            /** Items */
            items: components["schemas"]["CandidateOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[EmailLogOut] */
        Page_EmailLogOut_: {
            /** Items */
            items: components["schemas"]["EmailLogOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[InterviewSlotOut] */
        Page_InterviewSlotOut_: {
            /** Items */
            items: components["schemas"]["InterviewSlotOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[JobOut] */
        Page_JobOut_: {
            /** Items */
            items: components["schemas"]["JobOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[RankedCandidateOut] */
        Page_RankedCandidateOut_: {
            /** Items */
            items: components["schemas"]["RankedCandidateOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[TemplateOut] */
        Page_TemplateOut_: {
            /** Items */
            items: components["schemas"]["TemplateOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /**
         * ProcessStatusOut
         * @description total/processed/failed are computed over candidates.submission_status —
         *     there are no such columns on any table.
         */
        ProcessStatusOut: {
            status: components["schemas"]["TaskStatus"];
            /** Total */
            total: number;
            /** Processed */
            processed: number;
            /** Failed */
            failed: number;
            /** Error Message */
            error_message: string | null;
        };
        /**
         * PublicJobOut
         * @description Exposes only what a candidate needs. No recruiter identity, no job id,
         *     no counts — an unauthenticated caller has no business seeing any of that.
         *
         *     `fields` carries `TemplateFieldOut.field_id` (a UUID) and that is
         *     deliberate, not an oversight: `candidate_form_responses.field_id` is an
         *     FK, so US-12's submission payload must key answers by field_id — there is
         *     no other stable identifier (labels aren't unique, positions shift when a
         *     recruiter edits the template). It identifies a form field, not a
         *     recruiter, job, or tenant, and it isn't enumerable without the slug.
         */
        PublicJobOut: {
            /** Job Title */
            job_title: string;
            /** Job Description */
            job_description: string;
            /** Fields */
            fields: components["schemas"]["TemplateFieldOut"][];
            /** Is Accepting Responses */
            is_accepting_responses: boolean;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** RankedCandidateOut */
        RankedCandidateOut: {
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            /** Phone Number */
            phone_number: string | null;
            submission_status: components["schemas"]["SubmissionStatus"];
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Parse Error */
            parse_error: string | null;
            /** Resume Url */
            resume_url: string | null;
            /** Rank Position */
            rank_position: number;
            /** Semantic Score */
            semantic_score: number;
            /** Matched Skills */
            matched_skills: string[];
            /** Missing Skills */
            missing_skills: string[];
            /** Ai Feedback Summary */
            ai_feedback_summary: string | null;
        };
        /** RecruiterOut */
        RecruiterOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            account_state: components["schemas"]["RecruiterState"];
            /** Granted Scopes */
            granted_scopes: string[];
        };
        /**
         * RecruiterState
         * @enum {string}
         */
        RecruiterState: "ACTIVE" | "SUSPENDED" | "REAUTH_REQUIRED";
        /** RecruiterUpdate */
        RecruiterUpdate: {
            /** Full Name */
            full_name: string;
        };
        /** SchedulingPreferencesIn */
        SchedulingPreferencesIn: {
            /** Available Days */
            available_days: components["schemas"]["Weekday"][];
            /**
             * Available Start Time
             * Format: time
             */
            available_start_time: string;
            /**
             * Available End Time
             * Format: time
             */
            available_end_time: string;
            /** Slot Duration Minutes */
            slot_duration_minutes: number;
        };
        /** SchedulingPreferencesOut */
        SchedulingPreferencesOut: {
            /** Preference Id */
            preference_id: string | null;
            /** Available Days */
            available_days: components["schemas"]["Weekday"][];
            /**
             * Available Start Time
             * Format: time
             */
            available_start_time: string;
            /**
             * Available End Time
             * Format: time
             */
            available_end_time: string;
            /** Slot Duration Minutes */
            slot_duration_minutes: number;
            /** Timezone */
            timezone: string;
            /** Last Synced At */
            last_synced_at: string | null;
        };
        /**
         * SlotStatus
         * @enum {string}
         */
        SlotStatus: "PENDING" | "CONFIRMED" | "DECLINED" | "RESCHEDULED" | "CANCELLED";
        /**
         * SubmissionStatus
         * @enum {string}
         */
        SubmissionStatus: "SUBMITTED" | "PARSED" | "RANKED" | "INVITED" | "CONFIRMED" | "DECLINED" | "REJECTED" | "RESCHEDULED" | "PARSE_ERROR";
        /** TaskOut */
        TaskOut: {
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            task_type: components["schemas"]["TaskType"];
            status: components["schemas"]["TaskStatus"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Error Message */
            error_message: string | null;
            /** Result Summary */
            result_summary?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "PENDING" | "RUNNING" | "SUCCESS" | "FAILED" | "RETRIED";
        /**
         * TaskType
         * @enum {string}
         */
        TaskType: "RESUME_PARSE" | "BATCH_RANKING" | "EMAIL_DISPATCH" | "CALENDAR_SYNC" | "JD_EMBEDDING";
        /** TemplateCreate */
        TemplateCreate: {
            /** Template Name */
            template_name: string;
            /** Fields */
            fields: components["schemas"]["TemplateFieldIn"][];
        };
        /**
         * TemplateFieldIn
         * @description `field_id` present = keep this existing field row; absent = create a new
         *     one. Load-bearing: `candidate_form_responses.field_id` is an FK, so treating
         *     every save as delete-and-recreate would cascade away submitted responses.
         */
        TemplateFieldIn: {
            /** Field Id */
            field_id?: string | null;
            /** Field Label */
            field_label: string;
            field_type: components["schemas"]["FieldType"];
            /**
             * Is Required
             * @default false
             */
            is_required: boolean;
            /** Field Order */
            field_order: number;
            /** Options */
            options?: string[] | null;
        };
        /** TemplateFieldOut */
        TemplateFieldOut: {
            /**
             * Field Id
             * Format: uuid
             */
            field_id: string;
            /** Field Label */
            field_label: string;
            field_type: components["schemas"]["FieldType"];
            /** Is Required */
            is_required: boolean;
            /** Field Order */
            field_order: number;
            /** Options */
            options?: string[] | null;
        };
        /** TemplateOut */
        TemplateOut: {
            /**
             * Template Id
             * Format: uuid
             */
            template_id: string;
            /** Template Name */
            template_name: string;
            /** Fields */
            fields: components["schemas"]["TemplateFieldOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TemplateReplace */
        TemplateReplace: {
            /** Template Name */
            template_name: string;
            /** Fields */
            fields: components["schemas"]["TemplateFieldIn"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Weekday
         * @enum {string}
         */
        Weekday: "MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" | "SUNDAY";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    google_login_api_v1_auth_google_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    google_reconnect_api_v1_auth_google_reconnect_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_callback_api_v1_auth_google_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                autohire_oauth_state?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecruiterOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_me_api_v1_recruiters_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecruiterUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecruiterOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_v1_templates_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TemplateOut_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_template_api_v1_templates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_template_api_v1_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_template_api_v1_templates__template_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateReplace"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    delete_template_api_v1_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["JobStatus"] | null;
                q?: string | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_JobOut_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_job_api_v1_jobs__job_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    trigger_process_api_v1_jobs__job_id__process_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_status_api_v1_jobs__job_id__process_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessStatusOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_rank_api_v1_jobs__job_id__rank_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_public_job_api_v1_public_apply__apply_slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                apply_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicJobOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_application_api_v1_public_apply__apply_slug__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                apply_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_submit_application_api_v1_public_apply__apply_slug__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplySuccessOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    list_candidates_api_v1_jobs__job_id__candidates_get: {
        parameters: {
            query?: {
                submission_status?: components["schemas"]["SubmissionStatus"] | null;
                q?: string | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CandidateOut_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ranked_candidates_api_v1_jobs__job_id__candidates_ranked_get: {
        parameters: {
            query?: {
                min_score?: number | null;
                skill?: string | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RankedCandidateOut_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_candidate_api_v1_candidates__candidate_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateDetailOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_candidate_api_v1_candidates__candidate_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateDetailOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    download_resume_api_v1_candidates__candidate_id__resume_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preferences_api_v1_scheduling_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulingPreferencesOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_preferences_api_v1_scheduling_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchedulingPreferencesIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulingPreferencesOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    available_slots_api_v1_scheduling_available_slots_get: {
        parameters: {
            query?: {
                job_id?: string | null;
                count?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailableSlotOut"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_interviews_api_v1_interviews_get: {
        parameters: {
            query?: {
                job_id?: string | null;
                status?: components["schemas"]["SlotStatus"] | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_InterviewSlotOut_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedule_interviews_api_v1_interviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    update_interview_api_v1_interviews__slot_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewSlotUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewSlotOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    send_email_api_v1_emails_send_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailSendIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    list_emails_api_v1_emails_get: {
        parameters: {
            query?: {
                job_id?: string | null;
                candidate_id?: string | null;
                email_type?: components["schemas"]["EmailType"] | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                autohire_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EmailLogOut_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
